/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package vx.plt;

public class _VX_ProductInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _VX_ProductInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_VX_ProductInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VoxEngineJNI.delete__VX_ProductInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setProductName(String value) {
    VoxEngineJNI._VX_ProductInfo_productName_set(swigCPtr, this, value);
  }

  public String getProductName() {
    return VoxEngineJNI._VX_ProductInfo_productName_get(swigCPtr, this);
  }

  public void setMajorVersion(String value) {
    VoxEngineJNI._VX_ProductInfo_majorVersion_set(swigCPtr, this, value);
  }

  public String getMajorVersion() {
    return VoxEngineJNI._VX_ProductInfo_majorVersion_get(swigCPtr, this);
  }

  public void setMinorVersion(String value) {
    VoxEngineJNI._VX_ProductInfo_minorVersion_set(swigCPtr, this, value);
  }

  public String getMinorVersion() {
    return VoxEngineJNI._VX_ProductInfo_minorVersion_get(swigCPtr, this);
  }

  public void setBuildDate(String value) {
    VoxEngineJNI._VX_ProductInfo_buildDate_set(swigCPtr, this, value);
  }

  public String getBuildDate() {
    return VoxEngineJNI._VX_ProductInfo_buildDate_get(swigCPtr, this);
  }

  public _VX_ProductInfo() {
    this(VoxEngineJNI.new__VX_ProductInfo(), true);
  }

}
