/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package vx.plt;

public class SWIGTYPE_p__VX_ERROR {
  private transient long swigCPtr;

  protected SWIGTYPE_p__VX_ERROR(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  public  SWIGTYPE_p__VX_ERROR() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p__VX_ERROR obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

