/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package vx.plt;

public class VoxEngineJNI {
  public final static native void _VX_ProductInfo_productName_set(long jarg1, _VX_ProductInfo jarg1_, String jarg2);
  public final static native String _VX_ProductInfo_productName_get(long jarg1, _VX_ProductInfo jarg1_);
  public final static native void _VX_ProductInfo_majorVersion_set(long jarg1, _VX_ProductInfo jarg1_, String jarg2);
  public final static native String _VX_ProductInfo_majorVersion_get(long jarg1, _VX_ProductInfo jarg1_);
  public final static native void _VX_ProductInfo_minorVersion_set(long jarg1, _VX_ProductInfo jarg1_, String jarg2);
  public final static native String _VX_ProductInfo_minorVersion_get(long jarg1, _VX_ProductInfo jarg1_);
  public final static native void _VX_ProductInfo_buildDate_set(long jarg1, _VX_ProductInfo jarg1_, String jarg2);
  public final static native String _VX_ProductInfo_buildDate_get(long jarg1, _VX_ProductInfo jarg1_);
  public final static native long new__VX_ProductInfo();
  public final static native void delete__VX_ProductInfo(long jarg1);
  public final static native void VX_VoxAppSSL_eType_set(long jarg1, VX_VoxAppSSL jarg1_, int jarg2);
  public final static native int VX_VoxAppSSL_eType_get(long jarg1, VX_VoxAppSSL jarg1_);
  public final static native void VX_VoxAppSSL_iVpnTrigger_set(long jarg1, VX_VoxAppSSL jarg1_, int jarg2);
  public final static native int VX_VoxAppSSL_iVpnTrigger_get(long jarg1, VX_VoxAppSSL jarg1_);
  public final static native void VX_VoxAppSSL_iStarting_set(long jarg1, VX_VoxAppSSL jarg1_, int jarg2);
  public final static native int VX_VoxAppSSL_iStarting_get(long jarg1, VX_VoxAppSSL jarg1_);
  public final static native void VX_VoxAppSSL_iLength_set(long jarg1, VX_VoxAppSSL jarg1_, int jarg2);
  public final static native int VX_VoxAppSSL_iLength_get(long jarg1, VX_VoxAppSSL jarg1_);
  public final static native void VX_VoxAppSSL_iPrefTrigger_set(long jarg1, VX_VoxAppSSL jarg1_, int jarg2);
  public final static native int VX_VoxAppSSL_iPrefTrigger_get(long jarg1, VX_VoxAppSSL jarg1_);
  public final static native void VX_VoxAppSSL_iPrefValue_set(long jarg1, VX_VoxAppSSL jarg1_, int jarg2);
  public final static native int VX_VoxAppSSL_iPrefValue_get(long jarg1, VX_VoxAppSSL jarg1_);
  public final static native void VX_VoxAppSSL_iNoOfInnerPref_set(long jarg1, VX_VoxAppSSL jarg1_, int jarg2);
  public final static native int VX_VoxAppSSL_iNoOfInnerPref_get(long jarg1, VX_VoxAppSSL jarg1_);
  public final static native void VX_VoxAppSSL_iNoOfPref_set(long jarg1, VX_VoxAppSSL jarg1_, int jarg2);
  public final static native int VX_VoxAppSSL_iNoOfPref_get(long jarg1, VX_VoxAppSSL jarg1_);
  public final static native void VX_VoxAppSSL_iDiff_set(long jarg1, VX_VoxAppSSL jarg1_, int jarg2);
  public final static native int VX_VoxAppSSL_iDiff_get(long jarg1, VX_VoxAppSSL jarg1_);
  public final static native void VX_VoxAppSSL_oldkey_set(long jarg1, VX_VoxAppSSL jarg1_, String jarg2);
  public final static native String VX_VoxAppSSL_oldkey_get(long jarg1, VX_VoxAppSSL jarg1_);
  public final static native long new_VX_VoxAppSSL();
  public final static native void delete_VX_VoxAppSSL(long jarg1);
  public final static native void VX_AccountInfo_acc_id_set(long jarg1, VX_AccountInfo jarg1_, int jarg2);
  public final static native int VX_AccountInfo_acc_id_get(long jarg1, VX_AccountInfo jarg1_);
  public final static native void VX_AccountInfo_uri_set(long jarg1, VX_AccountInfo jarg1_, String jarg2);
  public final static native String VX_AccountInfo_uri_get(long jarg1, VX_AccountInfo jarg1_);
  public final static native void VX_AccountInfo_regUri_set(long jarg1, VX_AccountInfo jarg1_, String jarg2);
  public final static native String VX_AccountInfo_regUri_get(long jarg1, VX_AccountInfo jarg1_);
  public final static native void VX_AccountInfo_name_set(long jarg1, VX_AccountInfo jarg1_, String jarg2);
  public final static native String VX_AccountInfo_name_get(long jarg1, VX_AccountInfo jarg1_);
  public final static native void VX_AccountInfo_userName_set(long jarg1, VX_AccountInfo jarg1_, String jarg2);
  public final static native String VX_AccountInfo_userName_get(long jarg1, VX_AccountInfo jarg1_);
  public final static native void VX_AccountInfo_password_set(long jarg1, VX_AccountInfo jarg1_, String jarg2);
  public final static native String VX_AccountInfo_password_get(long jarg1, VX_AccountInfo jarg1_);
  public final static native void VX_AccountInfo_proxy_set(long jarg1, VX_AccountInfo jarg1_, String jarg2);
  public final static native String VX_AccountInfo_proxy_get(long jarg1, VX_AccountInfo jarg1_);
  public final static native void VX_AccountInfo_isDefault_set(long jarg1, VX_AccountInfo jarg1_, int jarg2);
  public final static native int VX_AccountInfo_isDefault_get(long jarg1, VX_AccountInfo jarg1_);
  public final static native void VX_AccountInfo_expires_set(long jarg1, VX_AccountInfo jarg1_, int jarg2);
  public final static native int VX_AccountInfo_expires_get(long jarg1, VX_AccountInfo jarg1_);
  public final static native void VX_AccountInfo_rtpPort_set(long jarg1, VX_AccountInfo jarg1_, int jarg2);
  public final static native int VX_AccountInfo_rtpPort_get(long jarg1, VX_AccountInfo jarg1_);
  public final static native void VX_AccountInfo_keepAlive_set(long jarg1, VX_AccountInfo jarg1_, int jarg2);
  public final static native int VX_AccountInfo_keepAlive_get(long jarg1, VX_AccountInfo jarg1_);
  public final static native void VX_AccountInfo_pc_set(long jarg1, VX_AccountInfo jarg1_, int jarg2);
  public final static native int VX_AccountInfo_pc_get(long jarg1, VX_AccountInfo jarg1_);
  public final static native void VX_AccountInfo_callerId_set(long jarg1, VX_AccountInfo jarg1_, String jarg2);
  public final static native String VX_AccountInfo_callerId_get(long jarg1, VX_AccountInfo jarg1_);
  public final static native long new_VX_AccountInfo();
  public final static native void delete_VX_AccountInfo(long jarg1);
  public final static native void VX_CallInfo_memberName_set(long jarg1, VX_CallInfo jarg1_, String jarg2);
  public final static native String VX_CallInfo_memberName_get(long jarg1, VX_CallInfo jarg1_);
  public final static native void VX_CallInfo_callState_set(long jarg1, VX_CallInfo jarg1_, int jarg2);
  public final static native int VX_CallInfo_callState_get(long jarg1, VX_CallInfo jarg1_);
  public final static native void VX_CallInfo_local_info_set(long jarg1, VX_CallInfo jarg1_, String jarg2);
  public final static native String VX_CallInfo_local_info_get(long jarg1, VX_CallInfo jarg1_);
  public final static native void VX_CallInfo_local_contact_set(long jarg1, VX_CallInfo jarg1_, String jarg2);
  public final static native String VX_CallInfo_local_contact_get(long jarg1, VX_CallInfo jarg1_);
  public final static native void VX_CallInfo_remote_info_set(long jarg1, VX_CallInfo jarg1_, String jarg2);
  public final static native String VX_CallInfo_remote_info_get(long jarg1, VX_CallInfo jarg1_);
  public final static native void VX_CallInfo_remote_contact_set(long jarg1, VX_CallInfo jarg1_, String jarg2);
  public final static native String VX_CallInfo_remote_contact_get(long jarg1, VX_CallInfo jarg1_);
  public final static native void VX_CallInfo_call_id_set(long jarg1, VX_CallInfo jarg1_, String jarg2);
  public final static native String VX_CallInfo_call_id_get(long jarg1, VX_CallInfo jarg1_);
  public final static native void VX_CallInfo_last_status_text_set(long jarg1, VX_CallInfo jarg1_, String jarg2);
  public final static native String VX_CallInfo_last_status_text_get(long jarg1, VX_CallInfo jarg1_);
  public final static native void VX_CallInfo_call_dump_set(long jarg1, VX_CallInfo jarg1_, String jarg2);
  public final static native String VX_CallInfo_call_dump_get(long jarg1, VX_CallInfo jarg1_);
  public final static native void VX_CallInfo_status_code_set(long jarg1, VX_CallInfo jarg1_, int jarg2);
  public final static native int VX_CallInfo_status_code_get(long jarg1, VX_CallInfo jarg1_);
  public final static native void VX_CallInfo_connect_duration_set(long jarg1, VX_CallInfo jarg1_, int jarg2);
  public final static native int VX_CallInfo_connect_duration_get(long jarg1, VX_CallInfo jarg1_);
  public final static native void VX_CallInfo_total_duration_set(long jarg1, VX_CallInfo jarg1_, int jarg2);
  public final static native int VX_CallInfo_total_duration_get(long jarg1, VX_CallInfo jarg1_);
  public final static native long new_VX_CallInfo();
  public final static native void delete_VX_CallInfo(long jarg1);
  public final static native void VX_SipConfig_noUDP_set(long jarg1, VX_SipConfig jarg1_, int jarg2);
  public final static native int VX_SipConfig_noUDP_get(long jarg1, VX_SipConfig jarg1_);
  public final static native void VX_SipConfig_noTCP_set(long jarg1, VX_SipConfig jarg1_, int jarg2);
  public final static native int VX_SipConfig_noTCP_get(long jarg1, VX_SipConfig jarg1_);
  public final static native void VX_SipConfig_publishEnabled_set(long jarg1, VX_SipConfig jarg1_, int jarg2);
  public final static native int VX_SipConfig_publishEnabled_get(long jarg1, VX_SipConfig jarg1_);
  public final static native void VX_SipConfig_vadEnabled_set(long jarg1, VX_SipConfig jarg1_, int jarg2);
  public final static native int VX_SipConfig_vadEnabled_get(long jarg1, VX_SipConfig jarg1_);
  public final static native void VX_SipConfig_pollingEventsEnabled_set(long jarg1, VX_SipConfig jarg1_, int jarg2);
  public final static native int VX_SipConfig_pollingEventsEnabled_get(long jarg1, VX_SipConfig jarg1_);
  public final static native void VX_SipConfig_imsEnabled_set(long jarg1, VX_SipConfig jarg1_, int jarg2);
  public final static native int VX_SipConfig_imsEnabled_get(long jarg1, VX_SipConfig jarg1_);
  public final static native void VX_SipConfig_imsIPSecHeaders_set(long jarg1, VX_SipConfig jarg1_, int jarg2);
  public final static native int VX_SipConfig_imsIPSecHeaders_get(long jarg1, VX_SipConfig jarg1_);
  public final static native void VX_SipConfig_imsIPSecTransport_set(long jarg1, VX_SipConfig jarg1_, int jarg2);
  public final static native int VX_SipConfig_imsIPSecTransport_get(long jarg1, VX_SipConfig jarg1_);
  public final static native void VX_SipConfig_listenPort_set(long jarg1, VX_SipConfig jarg1_, int jarg2);
  public final static native int VX_SipConfig_listenPort_get(long jarg1, VX_SipConfig jarg1_);
  public final static native void VX_SipConfig_expires_set(long jarg1, VX_SipConfig jarg1_, int jarg2);
  public final static native int VX_SipConfig_expires_get(long jarg1, VX_SipConfig jarg1_);
  public final static native void VX_SipConfig_ecTail_set(long jarg1, VX_SipConfig jarg1_, int jarg2);
  public final static native int VX_SipConfig_ecTail_get(long jarg1, VX_SipConfig jarg1_);
  public final static native void VX_SipConfig_logLevel_set(long jarg1, VX_SipConfig jarg1_, int jarg2);
  public final static native int VX_SipConfig_logLevel_get(long jarg1, VX_SipConfig jarg1_);
  public final static native void VX_SipConfig_stunAddress_set(long jarg1, VX_SipConfig jarg1_, String jarg2);
  public final static native String VX_SipConfig_stunAddress_get(long jarg1, VX_SipConfig jarg1_);
  public final static native void VX_SipConfig_nameServer_set(long jarg1, VX_SipConfig jarg1_, String jarg2);
  public final static native String VX_SipConfig_nameServer_get(long jarg1, VX_SipConfig jarg1_);
  public final static native long new_VX_SipConfig();
  public final static native void delete_VX_SipConfig(long jarg1);
  public final static native void VX_LogConfig_logLevel_set(long jarg1, VX_LogConfig jarg1_, int jarg2);
  public final static native int VX_LogConfig_logLevel_get(long jarg1, VX_LogConfig jarg1_);
  public final static native void VX_LogConfig_logfileName_set(long jarg1, VX_LogConfig jarg1_, String jarg2);
  public final static native String VX_LogConfig_logfileName_get(long jarg1, VX_LogConfig jarg1_);
  public final static native void VX_LogConfig_msg_logging_set(long jarg1, VX_LogConfig jarg1_, int jarg2);
  public final static native int VX_LogConfig_msg_logging_get(long jarg1, VX_LogConfig jarg1_);
  public final static native void VX_LogConfig_log_console_level_set(long jarg1, VX_LogConfig jarg1_, long jarg2);
  public final static native long VX_LogConfig_log_console_level_get(long jarg1, VX_LogConfig jarg1_);
  public final static native void VX_LogConfig_decor_set(long jarg1, VX_LogConfig jarg1_, long jarg2);
  public final static native long VX_LogConfig_decor_get(long jarg1, VX_LogConfig jarg1_);
  public final static native void VX_LogConfig_log_file_flags_set(long jarg1, VX_LogConfig jarg1_, long jarg2);
  public final static native long VX_LogConfig_log_file_flags_get(long jarg1, VX_LogConfig jarg1_);
  public final static native long new_VX_LogConfig();
  public final static native void delete_VX_LogConfig(long jarg1);
  public final static native void VX_PRESENCE_STATE_state_set(long jarg1, VX_PRESENCE_STATE jarg1_, int jarg2);
  public final static native int VX_PRESENCE_STATE_state_get(long jarg1, VX_PRESENCE_STATE jarg1_);
  public final static native void VX_PRESENCE_STATE_name_set(long jarg1, VX_PRESENCE_STATE jarg1_, String jarg2);
  public final static native String VX_PRESENCE_STATE_name_get(long jarg1, VX_PRESENCE_STATE jarg1_);
  public final static native long new_VX_PRESENCE_STATE();
  public final static native void delete_VX_PRESENCE_STATE(long jarg1);
  public final static native void VX_AccountMwiCfg_mwi_enabled_set(long jarg1, VX_AccountMwiCfg jarg1_, int jarg2);
  public final static native int VX_AccountMwiCfg_mwi_enabled_get(long jarg1, VX_AccountMwiCfg jarg1_);
  public final static native void VX_AccountMwiCfg_mwi_expires_set(long jarg1, VX_AccountMwiCfg jarg1_, long jarg2);
  public final static native long VX_AccountMwiCfg_mwi_expires_get(long jarg1, VX_AccountMwiCfg jarg1_);
  public final static native long new_VX_AccountMwiCfg();
  public final static native void delete_VX_AccountMwiCfg(long jarg1);
  public final static native void VX_CodecInfo_codecName_set(long jarg1, VX_CodecInfo jarg1_, String jarg2);
  public final static native String VX_CodecInfo_codecName_get(long jarg1, VX_CodecInfo jarg1_);
  public final static native void VX_CodecInfo_index_set(long jarg1, VX_CodecInfo jarg1_, int jarg2);
  public final static native int VX_CodecInfo_index_get(long jarg1, VX_CodecInfo jarg1_);
  public final static native long new_VX_CodecInfo();
  public final static native void delete_VX_CodecInfo(long jarg1);
  public final static native void VX_TransferInfo_callid_set(long jarg1, VX_TransferInfo jarg1_, long jarg2);
  public final static native long VX_TransferInfo_callid_get(long jarg1, VX_TransferInfo jarg1_);
  public final static native void VX_TransferInfo_vx_transferType_set(long jarg1, VX_TransferInfo jarg1_, int jarg2);
  public final static native int VX_TransferInfo_vx_transferType_get(long jarg1, VX_TransferInfo jarg1_);
  public final static native long new_VX_TransferInfo();
  public final static native void delete_VX_TransferInfo(long jarg1);
  public final static native void VX_AppCallBacks_onRegStateCb_set(long jarg1, VX_AppCallBacks jarg1_, long jarg2);
  public final static native long VX_AppCallBacks_onRegStateCb_get(long jarg1, VX_AppCallBacks jarg1_);
  public final static native void VX_AppCallBacks_onCallStateCb_set(long jarg1, VX_AppCallBacks jarg1_, long jarg2);
  public final static native long VX_AppCallBacks_onCallStateCb_get(long jarg1, VX_AppCallBacks jarg1_);
  public final static native void VX_AppCallBacks_onIncomingCallCb_set(long jarg1, VX_AppCallBacks jarg1_, long jarg2);
  public final static native long VX_AppCallBacks_onIncomingCallCb_get(long jarg1, VX_AppCallBacks jarg1_);
  public final static native void VX_AppCallBacks_onConfigDataCb_set(long jarg1, VX_AppCallBacks jarg1_, long jarg2);
  public final static native long VX_AppCallBacks_onConfigDataCb_get(long jarg1, VX_AppCallBacks jarg1_);
  public final static native void VX_AppCallBacks_onCallHoldConfCb_set(long jarg1, VX_AppCallBacks jarg1_, long jarg2);
  public final static native long VX_AppCallBacks_onCallHoldConfCb_get(long jarg1, VX_AppCallBacks jarg1_);
  public final static native void VX_AppCallBacks_onCallRetrieveConfCb_set(long jarg1, VX_AppCallBacks jarg1_, long jarg2);
  public final static native long VX_AppCallBacks_onCallRetrieveConfCb_get(long jarg1, VX_AppCallBacks jarg1_);
  public final static native void VX_AppCallBacks_onImReceivedCb_set(long jarg1, VX_AppCallBacks jarg1_, long jarg2);
  public final static native long VX_AppCallBacks_onImReceivedCb_get(long jarg1, VX_AppCallBacks jarg1_);
  public final static native void VX_AppCallBacks_onBuddyStatusCb_set(long jarg1, VX_AppCallBacks jarg1_, long jarg2);
  public final static native long VX_AppCallBacks_onBuddyStatusCb_get(long jarg1, VX_AppCallBacks jarg1_);
  public final static native void VX_AppCallBacks_onDtmfDigitCb_set(long jarg1, VX_AppCallBacks jarg1_, long jarg2);
  public final static native long VX_AppCallBacks_onDtmfDigitCb_get(long jarg1, VX_AppCallBacks jarg1_);
  public final static native void VX_AppCallBacks_onMwiCb_set(long jarg1, VX_AppCallBacks jarg1_, long jarg2);
  public final static native long VX_AppCallBacks_onMwiCb_get(long jarg1, VX_AppCallBacks jarg1_);
  public final static native void VX_AppCallBacks_onCallReplacedCb_set(long jarg1, VX_AppCallBacks jarg1_, long jarg2);
  public final static native long VX_AppCallBacks_onCallReplacedCb_get(long jarg1, VX_AppCallBacks jarg1_);
  public final static native void VX_AppCallBacks_onServerResponseCb_set(long jarg1, VX_AppCallBacks jarg1_, long jarg2);
  public final static native long VX_AppCallBacks_onServerResponseCb_get(long jarg1, VX_AppCallBacks jarg1_);
  public final static native void VX_AppCallBacks_onMediaStateCb_set(long jarg1, VX_AppCallBacks jarg1_, long jarg2);
  public final static native long VX_AppCallBacks_onMediaStateCb_get(long jarg1, VX_AppCallBacks jarg1_);
  public final static native long new_VX_AppCallBacks();
  public final static native void delete_VX_AppCallBacks(long jarg1);
  public final static native void VX_AppConfig_pTime_set(long jarg1, VX_AppConfig jarg1_, int jarg2);
  public final static native int VX_AppConfig_pTime_get(long jarg1, VX_AppConfig jarg1_);
  public final static native void VX_AppConfig_sipPort_set(long jarg1, VX_AppConfig jarg1_, int jarg2);
  public final static native int VX_AppConfig_sipPort_get(long jarg1, VX_AppConfig jarg1_);
  public final static native void VX_AppConfig_protCfg_set(long jarg1, VX_AppConfig jarg1_, int jarg2);
  public final static native int VX_AppConfig_protCfg_get(long jarg1, VX_AppConfig jarg1_);
  public final static native void VX_AppConfig_appSSL_set(long jarg1, VX_AppConfig jarg1_, long jarg2, VX_VoxAppSSL jarg2_);
  public final static native long VX_AppConfig_appSSL_get(long jarg1, VX_AppConfig jarg1_);
  public final static native void VX_AppConfig_logLevel_set(long jarg1, VX_AppConfig jarg1_, int jarg2);
  public final static native int VX_AppConfig_logLevel_get(long jarg1, VX_AppConfig jarg1_);
  public final static native void VX_AppConfig_max_calls_set(long jarg1, VX_AppConfig jarg1_, int jarg2);
  public final static native int VX_AppConfig_max_calls_get(long jarg1, VX_AppConfig jarg1_);
  public final static native void VX_AppConfig_logfileName_set(long jarg1, VX_AppConfig jarg1_, String jarg2);
  public final static native String VX_AppConfig_logfileName_get(long jarg1, VX_AppConfig jarg1_);
  public final static native void VX_AppConfig_appCbks_set(long jarg1, VX_AppConfig jarg1_, long jarg2, VX_AppCallBacks jarg2_);
  public final static native long VX_AppConfig_appCbks_get(long jarg1, VX_AppConfig jarg1_);
  public final static native void VX_AppConfig_user_agent_set(long jarg1, VX_AppConfig jarg1_, String jarg2);
  public final static native String VX_AppConfig_user_agent_get(long jarg1, VX_AppConfig jarg1_);
  public final static native void VX_AppConfig_ec_option_set(long jarg1, VX_AppConfig jarg1_, int jarg2);
  public final static native int VX_AppConfig_ec_option_get(long jarg1, VX_AppConfig jarg1_);
  public final static native void VX_AppConfig_jb_type_set(long jarg1, VX_AppConfig jarg1_, int jarg2);
  public final static native int VX_AppConfig_jb_type_get(long jarg1, VX_AppConfig jarg1_);
  public final static native void VX_AppConfig_interface_type_set(long jarg1, VX_AppConfig jarg1_, int jarg2);
  public final static native int VX_AppConfig_interface_type_get(long jarg1, VX_AppConfig jarg1_);
  public final static native void VX_AppConfig_isAECAvailable_set(long jarg1, VX_AppConfig jarg1_, int jarg2);
  public final static native int VX_AppConfig_isAECAvailable_get(long jarg1, VX_AppConfig jarg1_);
  public final static native void VX_AppConfig_isNSAvailable_set(long jarg1, VX_AppConfig jarg1_, int jarg2);
  public final static native int VX_AppConfig_isNSAvailable_get(long jarg1, VX_AppConfig jarg1_);
  public final static native void VX_AppConfig_isAGCAvailable_set(long jarg1, VX_AppConfig jarg1_, int jarg2);
  public final static native int VX_AppConfig_isAGCAvailable_get(long jarg1, VX_AppConfig jarg1_);
  public final static native void VX_AppConfig_ClockRate_set(long jarg1, VX_AppConfig jarg1_, int jarg2);
  public final static native int VX_AppConfig_ClockRate_get(long jarg1, VX_AppConfig jarg1_);
  public final static native void VX_AppConfig_isAndroid_2_x_Version_set(long jarg1, VX_AppConfig jarg1_, int jarg2);
  public final static native int VX_AppConfig_isAndroid_2_x_Version_get(long jarg1, VX_AppConfig jarg1_);
  public final static native void VX_AppConfig_stun_srv_count_set(long jarg1, VX_AppConfig jarg1_, int jarg2);
  public final static native int VX_AppConfig_stun_srv_count_get(long jarg1, VX_AppConfig jarg1_);
  public final static native void VX_AppConfig_app_name_set(long jarg1, VX_AppConfig jarg1_, String jarg2);
  public final static native String VX_AppConfig_app_name_get(long jarg1, VX_AppConfig jarg1_);
  public final static native long new_VX_AppConfig();
  public final static native void delete_VX_AppConfig(long jarg1);
  public final static native void delete_VX_AppCallback(long jarg1);
  public final static native void VX_AppCallback_onStarted(long jarg1, VX_AppCallback jarg1_, String jarg2);
  public final static native void VX_AppCallback_onStartedSwigExplicitVX_AppCallback(long jarg1, VX_AppCallback jarg1_, String jarg2);
  public final static native void VX_AppCallback_onStopped(long jarg1, VX_AppCallback jarg1_, int jarg2);
  public final static native void VX_AppCallback_onStoppedSwigExplicitVX_AppCallback(long jarg1, VX_AppCallback jarg1_, int jarg2);
  public final static native int VX_AppCallback_onRegStateCb(long jarg1, VX_AppCallback jarg1_, int jarg2, int jarg3);
  public final static native int VX_AppCallback_onRegStateCbSwigExplicitVX_AppCallback(long jarg1, VX_AppCallback jarg1_, int jarg2, int jarg3);
  public final static native int VX_AppCallback_onCallStateCb(long jarg1, VX_AppCallback jarg1_, int jarg2, int jarg3, long jarg4, VX_CallInfo jarg4_);
  public final static native int VX_AppCallback_onCallStateCbSwigExplicitVX_AppCallback(long jarg1, VX_AppCallback jarg1_, int jarg2, int jarg3, long jarg4, VX_CallInfo jarg4_);
  public final static native int VX_AppCallback_onMediaStateCb(long jarg1, VX_AppCallback jarg1_, int jarg2);
  public final static native int VX_AppCallback_onMediaStateCbSwigExplicitVX_AppCallback(long jarg1, VX_AppCallback jarg1_, int jarg2);
  public final static native int VX_AppCallback_onIncomingCallCb(long jarg1, VX_AppCallback jarg1_, int jarg2, String jarg3);
  public final static native int VX_AppCallback_onIncomingCallCbSwigExplicitVX_AppCallback(long jarg1, VX_AppCallback jarg1_, int jarg2, String jarg3);
  public final static native int VX_AppCallback_onConfigDataCb(long jarg1, VX_AppCallback jarg1_, int jarg2);
  public final static native int VX_AppCallback_onConfigDataCbSwigExplicitVX_AppCallback(long jarg1, VX_AppCallback jarg1_, int jarg2);
  public final static native int VX_AppCallback_onCallHoldConfCb(long jarg1, VX_AppCallback jarg1_, int jarg2);
  public final static native int VX_AppCallback_onCallHoldConfCbSwigExplicitVX_AppCallback(long jarg1, VX_AppCallback jarg1_, int jarg2);
  public final static native int VX_AppCallback_onCallRetrieveConfCb(long jarg1, VX_AppCallback jarg1_, int jarg2);
  public final static native int VX_AppCallback_onCallRetrieveConfCbSwigExplicitVX_AppCallback(long jarg1, VX_AppCallback jarg1_, int jarg2);
  public final static native int VX_AppCallback_onImReceivedCb(long jarg1, VX_AppCallback jarg1_, String jarg2, String jarg3);
  public final static native int VX_AppCallback_onImReceivedCbSwigExplicitVX_AppCallback(long jarg1, VX_AppCallback jarg1_, String jarg2, String jarg3);
  public final static native int VX_AppCallback_onBuddyStatusCb(long jarg1, VX_AppCallback jarg1_, int jarg2, int jarg3, String jarg4);
  public final static native int VX_AppCallback_onBuddyStatusCbSwigExplicitVX_AppCallback(long jarg1, VX_AppCallback jarg1_, int jarg2, int jarg3, String jarg4);
  public final static native int VX_AppCallback_onDtmfDigitCb(long jarg1, VX_AppCallback jarg1_, int jarg2, int jarg3);
  public final static native int VX_AppCallback_onDtmfDigitCbSwigExplicitVX_AppCallback(long jarg1, VX_AppCallback jarg1_, int jarg2, int jarg3);
  public final static native int VX_AppCallback_onMwiCb(long jarg1, VX_AppCallback jarg1_, int jarg2, String jarg3);
  public final static native int VX_AppCallback_onMwiCbSwigExplicitVX_AppCallback(long jarg1, VX_AppCallback jarg1_, int jarg2, String jarg3);
  public final static native int VX_AppCallback_onCallReplacedCb(long jarg1, VX_AppCallback jarg1_, int jarg2, int jarg3);
  public final static native int VX_AppCallback_onCallReplacedCbSwigExplicitVX_AppCallback(long jarg1, VX_AppCallback jarg1_, int jarg2, int jarg3);
  public final static native int VX_AppCallback_onServerResponseCb(long jarg1, VX_AppCallback jarg1_, int jarg2, int jarg3);
  public final static native int VX_AppCallback_onServerResponseCbSwigExplicitVX_AppCallback(long jarg1, VX_AppCallback jarg1_, int jarg2, int jarg3);
  public final static native void VX_AppCallback_onRecieveIMCb(long jarg1, VX_AppCallback jarg1_);
  public final static native void VX_AppCallback_onRecieveIMCbSwigExplicitVX_AppCallback(long jarg1, VX_AppCallback jarg1_);
  public final static native void VX_AppCallback_onCallMediaStateCb(long jarg1, VX_AppCallback jarg1_, int jarg2);
  public final static native void VX_AppCallback_onCallMediaStateCbSwigExplicitVX_AppCallback(long jarg1, VX_AppCallback jarg1_, int jarg2);
  public final static native long new_VX_AppCallback();
  public final static native void VX_AppCallback_director_connect(VX_AppCallback obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void VX_AppCallback_change_ownership(VX_AppCallback obj, long cptr, boolean take_or_release);
  public final static native int JNI_VX_vid_win_rotate(int jarg1, int jarg2);
  public final static native int JNI_VX_recorder_create(String jarg1, int jarg2, int jarg3, int jarg4, int jarg5);
  public final static native int JNI_VX_recorder_get_conf_port();
  public final static native void JNI_VX_recorder_destroy();
  public final static native void setCallbackObject(long jarg1, VX_AppCallback jarg1_);
  public final static native void setIncomingVideoRenderer(Object jarg1);
  public final static native int JNI_VX_InitializeApp(long jarg1, VX_AppConfig jarg1_, long jarg2);
  public final static native int JNI_VX_RegisterAccount(long jarg1, VX_AccountInfo jarg1_, long jarg2);
  public final static native int JNI_VX_UnRegisterAccount(int jarg1, long jarg2);
  public final static native int JNI_VX_IsAccountActive(int jarg1, long jarg2);
  public final static native int JNI_VX_ShutdownApp(long jarg1);
  public final static native int JNI_VX_MakeCall(int jarg1, String jarg2, int jarg3, long jarg4);
  public final static native int JNI_VX_ReleaseCall(int jarg1, long jarg2);
  public final static native int JNI_VX_AnswerCall(int jarg1, int jarg2, long jarg3);
  public final static native int JNI_VX_DialDtmf(int jarg1, String jarg2, int jarg3, long jarg4);
  public final static native int JNI_VX_ResumeCall(int jarg1, long jarg2);
  public final static native int JNI_VX_GetCodecs(long jarg1, VX_CodecInfo jarg1_, int jarg2, long jarg3);
  public final static native int JNI_VX_GetCurrentCodec(long jarg1, VX_CodecInfo jarg1_, long jarg2);
  public final static native int JNI_VX_SetCodecPriority(String jarg1, int jarg2, long jarg3);
  public final static native int JNI_VX_SetSIPEncryptionConfiguration(long jarg1, VX_VoxAppSSL jarg1_, long jarg2);
  public final static native int JNI_VX_SetRTPEncryptionConfiguration(long jarg1, VX_VoxAppSSL jarg1_, long jarg2);
  public final static native int JNI_VX_HoldCall(int jarg1, long jarg2);
  public final static native int JNI_VX_IsLocalHold(int jarg1, long jarg2);
  public final static native int JNI_VX_IsRemoteHold(int jarg1, long jarg2);
  public final static native int JNI_VX_TransferCall(int jarg1, String jarg2, long jarg3);
  public final static native int JNI_VX_TransferCallWithReplaces(int jarg1, int jarg2, long jarg3);
  public final static native int JNI_VX_GetMaxCallCount(long jarg1);
  public final static native int JNI_VX_GetCallCount(long jarg1);
  public final static native int JNI_VX_IsCallActive(int jarg1, long jarg2);
  public final static native int JNI_VX_IsAppInitialized(long jarg1);
  public final static native int JNI_VX_IsCallHasMedia(int jarg1, long jarg2);
  public final static native int JNI_VX_ReleaseAllCalls(long jarg1);
  public final static native int JNI_VX_MuteCall(long jarg1);
  public final static native int JNI_VX_UnMuteCall(long jarg1, float jarg2);
  public final static native int JNI_VXGetConfPort(int jarg1, long jarg2);
  public final static native int JNI_VX_ConferenceConnect(int jarg1, int jarg2, long jarg3);
  public final static native int JNI_VX_ConferenceDisconnect(int jarg1, int jarg2, long jarg3);
  public final static native int JNI_VX_SetLogConfig(long jarg1, VX_LogConfig jarg1_, long jarg2);
  public final static native int JNI_VX_IsFeatureSupported(int jarg1, long jarg2);
  public final static native int JNI_VX_GetConfPort(int jarg1, long jarg2);
  public final static native int JNI_VX_MakeConference(int jarg1, long jarg2);
  public final static native int JNI_VX_GetCallInfo(int jarg1, long jarg2, VX_CallInfo jarg2_, long jarg3);
  public final static native int JNI_VX_Adjust_rx_level(int jarg1, float jarg2);
  public final static native int JNI_VX_Adjust_tx_level(int jarg1, float jarg2);
  public final static native int JNI_VX_Get_signal_level(int jarg1, String jarg2, String jarg3);

  public static void SwigDirector_VX_AppCallback_onStarted(VX_AppCallback jself, String msg) {
    jself.onStarted(msg);
  }
  public static void SwigDirector_VX_AppCallback_onStopped(VX_AppCallback jself, int restart) {
    jself.onStopped(restart);
  }
  public static int SwigDirector_VX_AppCallback_onRegStateCb(VX_AppCallback jself, int arg0, int arg1) {
    return jself.onRegStateCb(arg0, arg1);
  }
  public static int SwigDirector_VX_AppCallback_onCallStateCb(VX_AppCallback jself, int arg0, int arg1, long arg2) {
    return jself.onCallStateCb(arg0, arg1, (arg2 == 0) ? null : new VX_CallInfo(arg2, false));
  }
  public static int SwigDirector_VX_AppCallback_onMediaStateCb(VX_AppCallback jself, int arg0) {
    return jself.onMediaStateCb(arg0);
  }
  public static int SwigDirector_VX_AppCallback_onIncomingCallCb(VX_AppCallback jself, int arg0, String arg1) {
    return jself.onIncomingCallCb(arg0, arg1);
  }
  public static int SwigDirector_VX_AppCallback_onConfigDataCb(VX_AppCallback jself, int arg1) {
    return jself.onConfigDataCb(arg1);
  }
  public static int SwigDirector_VX_AppCallback_onCallHoldConfCb(VX_AppCallback jself, int arg1) {
    return jself.onCallHoldConfCb(arg1);
  }
  public static int SwigDirector_VX_AppCallback_onCallRetrieveConfCb(VX_AppCallback jself, int arg1) {
    return jself.onCallRetrieveConfCb(arg1);
  }
  public static int SwigDirector_VX_AppCallback_onImReceivedCb(VX_AppCallback jself, String arg1, String arg2) {
    return jself.onImReceivedCb(arg1, arg2);
  }
  public static int SwigDirector_VX_AppCallback_onBuddyStatusCb(VX_AppCallback jself, int arg1, int arg2, String arg3) {
    return jself.onBuddyStatusCb(arg1, arg2, arg3);
  }
  public static int SwigDirector_VX_AppCallback_onDtmfDigitCb(VX_AppCallback jself, int arg1, int arg2) {
    return jself.onDtmfDigitCb(arg1, arg2);
  }
  public static int SwigDirector_VX_AppCallback_onMwiCb(VX_AppCallback jself, int arg1, String arg2) {
    return jself.onMwiCb(arg1, arg2);
  }
  public static int SwigDirector_VX_AppCallback_onCallReplacedCb(VX_AppCallback jself, int arg1, int arg2) {
    return jself.onCallReplacedCb(arg1, arg2);
  }
  public static int SwigDirector_VX_AppCallback_onServerResponseCb(VX_AppCallback jself, int arg1, int arg2) {
    return jself.onServerResponseCb(arg1, arg2);
  }
  public static void SwigDirector_VX_AppCallback_onRecieveIMCb(VX_AppCallback jself) {
    jself.onRecieveIMCb();
  }
  public static void SwigDirector_VX_AppCallback_onCallMediaStateCb(VX_AppCallback jself, int callid) {
    jself.onCallMediaStateCb(callid);
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
