/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package vx.plt;

public class VoxEngine implements VoxEngineConstants {
  public static int JNI_VX_vid_win_rotate(int callid, int angle) {
    return VoxEngineJNI.JNI_VX_vid_win_rotate(callid, angle);
  }

  public static int JNI_VX_recorder_create(String filename, int enc_type, int max_size, int options, int p_id) {
    return VoxEngineJNI.JNI_VX_recorder_create(filename, enc_type, max_size, options, p_id);
  }

  public static int JNI_VX_recorder_get_conf_port() {
    return VoxEngineJNI.JNI_VX_recorder_get_conf_port();
  }

  public static void JNI_VX_recorder_destroy() {
    VoxEngineJNI.JNI_VX_recorder_destroy();
  }

  public static void setCallbackObject(VX_AppCallback callback) {
    VoxEngineJNI.setCallbackObject(VX_AppCallback.getCPtr(callback), callback);
  }

  public static void setIncomingVideoRenderer(Object surface) {
    VoxEngineJNI.setIncomingVideoRenderer(surface);
  }

  public static int JNI_VX_InitializeApp(VX_AppConfig pAppConfig, SWIGTYPE_p__VX_ERROR eError) {
    return VoxEngineJNI.JNI_VX_InitializeApp(VX_AppConfig.getCPtr(pAppConfig), pAppConfig, SWIGTYPE_p__VX_ERROR.getCPtr(eError));
  }

  public static int JNI_VX_RegisterAccount(VX_AccountInfo pAccountInfo, SWIGTYPE_p__VX_ERROR eError) {
    return VoxEngineJNI.JNI_VX_RegisterAccount(VX_AccountInfo.getCPtr(pAccountInfo), pAccountInfo, SWIGTYPE_p__VX_ERROR.getCPtr(eError));
  }

  public static int JNI_VX_UnRegisterAccount(int accId, SWIGTYPE_p__VX_ERROR eError) {
    return VoxEngineJNI.JNI_VX_UnRegisterAccount(accId, SWIGTYPE_p__VX_ERROR.getCPtr(eError));
  }

  public static int JNI_VX_IsAccountActive(int accId, SWIGTYPE_p__VX_ERROR eError) {
    return VoxEngineJNI.JNI_VX_IsAccountActive(accId, SWIGTYPE_p__VX_ERROR.getCPtr(eError));
  }

  public static int JNI_VX_ShutdownApp(SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_ShutdownApp(SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_MakeCall(int iAccId, String pUri, VX_MediaType type, SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_MakeCall(iAccId, pUri, type.swigValue(), SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_ReleaseCall(int iCallId, SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_ReleaseCall(iCallId, SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_AnswerCall(int iCallId, int iCode, SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_AnswerCall(iCallId, iCode, SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_DialDtmf(int callId, String digits, int mode, SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_DialDtmf(callId, digits, mode, SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_ResumeCall(int iCallId, SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_ResumeCall(iCallId, SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_GetCodecs(VX_CodecInfo pCodec, int size, SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_GetCodecs(VX_CodecInfo.getCPtr(pCodec), pCodec, size, SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_GetCurrentCodec(VX_CodecInfo codec, SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_GetCurrentCodec(VX_CodecInfo.getCPtr(codec), codec, SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_SetCodecPriority(String pName, int iIndex, SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_SetCodecPriority(pName, iIndex, SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_SetSIPEncryptionConfiguration(VX_VoxAppSSL voxAppSsl, SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_SetSIPEncryptionConfiguration(VX_VoxAppSSL.getCPtr(voxAppSsl), voxAppSsl, SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_SetRTPEncryptionConfiguration(VX_VoxAppSSL voxAppSsl, SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_SetRTPEncryptionConfiguration(VX_VoxAppSSL.getCPtr(voxAppSsl), voxAppSsl, SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_HoldCall(int iCallId, SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_HoldCall(iCallId, SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_IsLocalHold(int iCallId, SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_IsLocalHold(iCallId, SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_IsRemoteHold(int iCallId, SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_IsRemoteHold(iCallId, SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_TransferCall(int callid, String uri, SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_TransferCall(callid, uri, SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_TransferCallWithReplaces(int callId, int dstSession, SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_TransferCallWithReplaces(callId, dstSession, SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_GetMaxCallCount(SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_GetMaxCallCount(SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_GetCallCount(SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_GetCallCount(SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_IsCallActive(int callid, SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_IsCallActive(callid, SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_IsAppInitialized(SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_IsAppInitialized(SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_IsCallHasMedia(int callid, SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_IsCallHasMedia(callid, SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_ReleaseAllCalls(SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_ReleaseAllCalls(SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_MuteCall(SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_MuteCall(SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_UnMuteCall(SWIGTYPE_p__VX_ERROR peError, float level) {
    return VoxEngineJNI.JNI_VX_UnMuteCall(SWIGTYPE_p__VX_ERROR.getCPtr(peError), level);
  }

  public static int JNI_VXGetConfPort(int call_id, SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VXGetConfPort(call_id, SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_ConferenceConnect(int sourceport, int sink, SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_ConferenceConnect(sourceport, sink, SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_ConferenceDisconnect(int sourceport, int sink, SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_ConferenceDisconnect(sourceport, sink, SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_SetLogConfig(VX_LogConfig lcfg, SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_SetLogConfig(VX_LogConfig.getCPtr(lcfg), lcfg, SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_IsFeatureSupported(VX_FEATURE feature, SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_IsFeatureSupported(feature.swigValue(), SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_GetConfPort(int callId, SWIGTYPE_p__VX_ERROR eError) {
    return VoxEngineJNI.JNI_VX_GetConfPort(callId, SWIGTYPE_p__VX_ERROR.getCPtr(eError));
  }

  public static int JNI_VX_MakeConference(int callId, SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_MakeConference(callId, SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_GetCallInfo(int iCallId, VX_CallInfo callInfo, SWIGTYPE_p__VX_ERROR peError) {
    return VoxEngineJNI.JNI_VX_GetCallInfo(iCallId, VX_CallInfo.getCPtr(callInfo), callInfo, SWIGTYPE_p__VX_ERROR.getCPtr(peError));
  }

  public static int JNI_VX_Adjust_rx_level(int slot, float level) {
    return VoxEngineJNI.JNI_VX_Adjust_rx_level(slot, level);
  }

  public static int JNI_VX_Adjust_tx_level(int slot, float level) {
    return VoxEngineJNI.JNI_VX_Adjust_tx_level(slot, level);
  }

  public static int JNI_VX_Get_signal_level(int slot, String tx_level, String rx_level) {
    return VoxEngineJNI.JNI_VX_Get_signal_level(slot, tx_level, rx_level);
  }

}
