/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package vx.plt;

public interface VoxEngineConstants {
  public final static int _VX_FALSE = -1;
  public final static int _VX_TRUE = 0;
  public final static int VX_FALSE = -1;
  public final static int VX_TRUE = 0;
  public final static int VX_MAX_MAJOR_VERSION_SIZE = 50;
  public final static int VX_MAX_MINOR_VERSION_SIZE = 50;
  public final static int VX_MAX_PRODUCT_NAME_SIZE = 50;
  public final static int VX_MAX_BUILD_DATE_SIZE = 50;
  public final static int VX_MAX_URI_SIZE = 50;
  public final static int VX_MAX_NAME_SIZE = 50;
  public final static int VX_MAX_PWD_SIZE = 50;
  public final static int VX_MAX_PROXY_SIZE = 50;
  public final static int VX_MAX_OLD_KEY_LENGTH = 50;
  public final static int VX_CODEC_MAX_LENGTH = 20;
  public final static int VX_TRANSFER_MAX_LENGTH = 2;
  public final static int VX_MAX_STUN_ADDRESS = 255;
  public final static int VX_MAX_NAME_SERVER = 255;
}
