/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package vx.plt;

public class VX_AccountInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VX_AccountInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VX_AccountInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VoxEngineJNI.delete_VX_AccountInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAcc_id(int value) {
    VoxEngineJNI.VX_AccountInfo_acc_id_set(swigCPtr, this, value);
  }

  public int getAcc_id() {
    return VoxEngineJNI.VX_AccountInfo_acc_id_get(swigCPtr, this);
  }

  public void setUri(String value) {
    VoxEngineJNI.VX_AccountInfo_uri_set(swigCPtr, this, value);
  }

  public String getUri() {
    return VoxEngineJNI.VX_AccountInfo_uri_get(swigCPtr, this);
  }

  public void setRegUri(String value) {
    VoxEngineJNI.VX_AccountInfo_regUri_set(swigCPtr, this, value);
  }

  public String getRegUri() {
    return VoxEngineJNI.VX_AccountInfo_regUri_get(swigCPtr, this);
  }

  public void setName(String value) {
    VoxEngineJNI.VX_AccountInfo_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return VoxEngineJNI.VX_AccountInfo_name_get(swigCPtr, this);
  }

  public void setUserName(String value) {
    VoxEngineJNI.VX_AccountInfo_userName_set(swigCPtr, this, value);
  }

  public String getUserName() {
    return VoxEngineJNI.VX_AccountInfo_userName_get(swigCPtr, this);
  }

  public void setPassword(String value) {
    VoxEngineJNI.VX_AccountInfo_password_set(swigCPtr, this, value);
  }

  public String getPassword() {
    return VoxEngineJNI.VX_AccountInfo_password_get(swigCPtr, this);
  }

  public void setProxy(String value) {
    VoxEngineJNI.VX_AccountInfo_proxy_set(swigCPtr, this, value);
  }

  public String getProxy() {
    return VoxEngineJNI.VX_AccountInfo_proxy_get(swigCPtr, this);
  }

  public void setIsDefault(int value) {
    VoxEngineJNI.VX_AccountInfo_isDefault_set(swigCPtr, this, value);
  }

  public int getIsDefault() {
    return VoxEngineJNI.VX_AccountInfo_isDefault_get(swigCPtr, this);
  }

  public void setExpires(int value) {
    VoxEngineJNI.VX_AccountInfo_expires_set(swigCPtr, this, value);
  }

  public int getExpires() {
    return VoxEngineJNI.VX_AccountInfo_expires_get(swigCPtr, this);
  }

  public void setRtpPort(int value) {
    VoxEngineJNI.VX_AccountInfo_rtpPort_set(swigCPtr, this, value);
  }

  public int getRtpPort() {
    return VoxEngineJNI.VX_AccountInfo_rtpPort_get(swigCPtr, this);
  }

  public void setKeepAlive(int value) {
    VoxEngineJNI.VX_AccountInfo_keepAlive_set(swigCPtr, this, value);
  }

  public int getKeepAlive() {
    return VoxEngineJNI.VX_AccountInfo_keepAlive_get(swigCPtr, this);
  }

  public void setPc(int value) {
    VoxEngineJNI.VX_AccountInfo_pc_set(swigCPtr, this, value);
  }

  public int getPc() {
    return VoxEngineJNI.VX_AccountInfo_pc_get(swigCPtr, this);
  }

  public void setCallerId(String value) {
    VoxEngineJNI.VX_AccountInfo_callerId_set(swigCPtr, this, value);
  }

  public String getCallerId() {
    return VoxEngineJNI.VX_AccountInfo_callerId_get(swigCPtr, this);
  }

  public VX_AccountInfo() {
    this(VoxEngineJNI.new_VX_AccountInfo(), true);
  }

}
