/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package vx.plt;

public class VX_AccountMwiCfg {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VX_AccountMwiCfg(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VX_AccountMwiCfg obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VoxEngineJNI.delete_VX_AccountMwiCfg(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMwi_enabled(int value) {
    VoxEngineJNI.VX_AccountMwiCfg_mwi_enabled_set(swigCPtr, this, value);
  }

  public int getMwi_enabled() {
    return VoxEngineJNI.VX_AccountMwiCfg_mwi_enabled_get(swigCPtr, this);
  }

  public void setMwi_expires(long value) {
    VoxEngineJNI.VX_AccountMwiCfg_mwi_expires_set(swigCPtr, this, value);
  }

  public long getMwi_expires() {
    return VoxEngineJNI.VX_AccountMwiCfg_mwi_expires_get(swigCPtr, this);
  }

  public VX_AccountMwiCfg() {
    this(VoxEngineJNI.new_VX_AccountMwiCfg(), true);
  }

}
