/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package vx.plt;

public class VX_AppCallback {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VX_AppCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VX_AppCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VoxEngineJNI.delete_VX_AppCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    VoxEngineJNI.VX_AppCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    VoxEngineJNI.VX_AppCallback_change_ownership(this, swigCPtr, true);
  }

  public void onStarted(String msg) {
    if (getClass() == VX_AppCallback.class) VoxEngineJNI.VX_AppCallback_onStarted(swigCPtr, this, msg); else VoxEngineJNI.VX_AppCallback_onStartedSwigExplicitVX_AppCallback(swigCPtr, this, msg);
  }

  public void onStopped(int restart) {
    if (getClass() == VX_AppCallback.class) VoxEngineJNI.VX_AppCallback_onStopped(swigCPtr, this, restart); else VoxEngineJNI.VX_AppCallback_onStoppedSwigExplicitVX_AppCallback(swigCPtr, this, restart);
  }

  public int onRegStateCb(int arg0, int arg1) {
    return (getClass() == VX_AppCallback.class) ? VoxEngineJNI.VX_AppCallback_onRegStateCb(swigCPtr, this, arg0, arg1) : VoxEngineJNI.VX_AppCallback_onRegStateCbSwigExplicitVX_AppCallback(swigCPtr, this, arg0, arg1);
  }

  public int onCallStateCb(int arg0, int arg1, VX_CallInfo arg2) {
    return (getClass() == VX_AppCallback.class) ? VoxEngineJNI.VX_AppCallback_onCallStateCb(swigCPtr, this, arg0, arg1, VX_CallInfo.getCPtr(arg2), arg2) : VoxEngineJNI.VX_AppCallback_onCallStateCbSwigExplicitVX_AppCallback(swigCPtr, this, arg0, arg1, VX_CallInfo.getCPtr(arg2), arg2);
  }

  public int onMediaStateCb(int arg0) {
    return (getClass() == VX_AppCallback.class) ? VoxEngineJNI.VX_AppCallback_onMediaStateCb(swigCPtr, this, arg0) : VoxEngineJNI.VX_AppCallback_onMediaStateCbSwigExplicitVX_AppCallback(swigCPtr, this, arg0);
  }

  public int onIncomingCallCb(int arg0, String arg1) {
    return (getClass() == VX_AppCallback.class) ? VoxEngineJNI.VX_AppCallback_onIncomingCallCb(swigCPtr, this, arg0, arg1) : VoxEngineJNI.VX_AppCallback_onIncomingCallCbSwigExplicitVX_AppCallback(swigCPtr, this, arg0, arg1);
  }

  public int onConfigDataCb(int arg1) {
    return (getClass() == VX_AppCallback.class) ? VoxEngineJNI.VX_AppCallback_onConfigDataCb(swigCPtr, this, arg1) : VoxEngineJNI.VX_AppCallback_onConfigDataCbSwigExplicitVX_AppCallback(swigCPtr, this, arg1);
  }

  public int onCallHoldConfCb(int arg1) {
    return (getClass() == VX_AppCallback.class) ? VoxEngineJNI.VX_AppCallback_onCallHoldConfCb(swigCPtr, this, arg1) : VoxEngineJNI.VX_AppCallback_onCallHoldConfCbSwigExplicitVX_AppCallback(swigCPtr, this, arg1);
  }

  public int onCallRetrieveConfCb(int arg1) {
    return (getClass() == VX_AppCallback.class) ? VoxEngineJNI.VX_AppCallback_onCallRetrieveConfCb(swigCPtr, this, arg1) : VoxEngineJNI.VX_AppCallback_onCallRetrieveConfCbSwigExplicitVX_AppCallback(swigCPtr, this, arg1);
  }

  public int onImReceivedCb(String arg1, String arg2) {
    return (getClass() == VX_AppCallback.class) ? VoxEngineJNI.VX_AppCallback_onImReceivedCb(swigCPtr, this, arg1, arg2) : VoxEngineJNI.VX_AppCallback_onImReceivedCbSwigExplicitVX_AppCallback(swigCPtr, this, arg1, arg2);
  }

  public int onBuddyStatusCb(int arg1, int arg2, String arg3) {
    return (getClass() == VX_AppCallback.class) ? VoxEngineJNI.VX_AppCallback_onBuddyStatusCb(swigCPtr, this, arg1, arg2, arg3) : VoxEngineJNI.VX_AppCallback_onBuddyStatusCbSwigExplicitVX_AppCallback(swigCPtr, this, arg1, arg2, arg3);
  }

  public int onDtmfDigitCb(int arg1, int arg2) {
    return (getClass() == VX_AppCallback.class) ? VoxEngineJNI.VX_AppCallback_onDtmfDigitCb(swigCPtr, this, arg1, arg2) : VoxEngineJNI.VX_AppCallback_onDtmfDigitCbSwigExplicitVX_AppCallback(swigCPtr, this, arg1, arg2);
  }

  public int onMwiCb(int arg1, String arg2) {
    return (getClass() == VX_AppCallback.class) ? VoxEngineJNI.VX_AppCallback_onMwiCb(swigCPtr, this, arg1, arg2) : VoxEngineJNI.VX_AppCallback_onMwiCbSwigExplicitVX_AppCallback(swigCPtr, this, arg1, arg2);
  }

  public int onCallReplacedCb(int arg1, int arg2) {
    return (getClass() == VX_AppCallback.class) ? VoxEngineJNI.VX_AppCallback_onCallReplacedCb(swigCPtr, this, arg1, arg2) : VoxEngineJNI.VX_AppCallback_onCallReplacedCbSwigExplicitVX_AppCallback(swigCPtr, this, arg1, arg2);
  }

  public int onServerResponseCb(int arg1, int arg2) {
    return (getClass() == VX_AppCallback.class) ? VoxEngineJNI.VX_AppCallback_onServerResponseCb(swigCPtr, this, arg1, arg2) : VoxEngineJNI.VX_AppCallback_onServerResponseCbSwigExplicitVX_AppCallback(swigCPtr, this, arg1, arg2);
  }

  public void onRecieveIMCb() {
    if (getClass() == VX_AppCallback.class) VoxEngineJNI.VX_AppCallback_onRecieveIMCb(swigCPtr, this); else VoxEngineJNI.VX_AppCallback_onRecieveIMCbSwigExplicitVX_AppCallback(swigCPtr, this);
  }

  public void onCallMediaStateCb(int callid) {
    if (getClass() == VX_AppCallback.class) VoxEngineJNI.VX_AppCallback_onCallMediaStateCb(swigCPtr, this, callid); else VoxEngineJNI.VX_AppCallback_onCallMediaStateCbSwigExplicitVX_AppCallback(swigCPtr, this, callid);
  }

  public VX_AppCallback() {
    this(VoxEngineJNI.new_VX_AppCallback(), true);
    VoxEngineJNI.VX_AppCallback_director_connect(this, swigCPtr, true, true);
  }

}
