/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package vx.plt;

public class VX_AppCallBacks {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VX_AppCallBacks(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VX_AppCallBacks obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VoxEngineJNI.delete_VX_AppCallBacks(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOnRegStateCb(SWIGTYPE_p_f_int_int__int value) {
    VoxEngineJNI.VX_AppCallBacks_onRegStateCb_set(swigCPtr, this, SWIGTYPE_p_f_int_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_int_int__int getOnRegStateCb() {
    long cPtr = VoxEngineJNI.VX_AppCallBacks_onRegStateCb_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int_int__int(cPtr, false);
  }

  public void setOnCallStateCb(SWIGTYPE_p_f_int_int_p__VX_CallInfo__int value) {
    VoxEngineJNI.VX_AppCallBacks_onCallStateCb_set(swigCPtr, this, SWIGTYPE_p_f_int_int_p__VX_CallInfo__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_int_int_p__VX_CallInfo__int getOnCallStateCb() {
    long cPtr = VoxEngineJNI.VX_AppCallBacks_onCallStateCb_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int_int_p__VX_CallInfo__int(cPtr, false);
  }

  public void setOnIncomingCallCb(SWIGTYPE_p_f_int_p_char__int value) {
    VoxEngineJNI.VX_AppCallBacks_onIncomingCallCb_set(swigCPtr, this, SWIGTYPE_p_f_int_p_char__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_int_p_char__int getOnIncomingCallCb() {
    long cPtr = VoxEngineJNI.VX_AppCallBacks_onIncomingCallCb_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int_p_char__int(cPtr, false);
  }

  public void setOnConfigDataCb(SWIGTYPE_p_f_int__int value) {
    VoxEngineJNI.VX_AppCallBacks_onConfigDataCb_set(swigCPtr, this, SWIGTYPE_p_f_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_int__int getOnConfigDataCb() {
    long cPtr = VoxEngineJNI.VX_AppCallBacks_onConfigDataCb_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int__int(cPtr, false);
  }

  public void setOnCallHoldConfCb(SWIGTYPE_p_f_int__int value) {
    VoxEngineJNI.VX_AppCallBacks_onCallHoldConfCb_set(swigCPtr, this, SWIGTYPE_p_f_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_int__int getOnCallHoldConfCb() {
    long cPtr = VoxEngineJNI.VX_AppCallBacks_onCallHoldConfCb_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int__int(cPtr, false);
  }

  public void setOnCallRetrieveConfCb(SWIGTYPE_p_f_int__int value) {
    VoxEngineJNI.VX_AppCallBacks_onCallRetrieveConfCb_set(swigCPtr, this, SWIGTYPE_p_f_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_int__int getOnCallRetrieveConfCb() {
    long cPtr = VoxEngineJNI.VX_AppCallBacks_onCallRetrieveConfCb_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int__int(cPtr, false);
  }

  public void setOnImReceivedCb(SWIGTYPE_p_f_p_char_p_char__int value) {
    VoxEngineJNI.VX_AppCallBacks_onImReceivedCb_set(swigCPtr, this, SWIGTYPE_p_f_p_char_p_char__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_char_p_char__int getOnImReceivedCb() {
    long cPtr = VoxEngineJNI.VX_AppCallBacks_onImReceivedCb_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_char_p_char__int(cPtr, false);
  }

  public void setOnBuddyStatusCb(SWIGTYPE_p_f_int_int_p_q_const__char__int value) {
    VoxEngineJNI.VX_AppCallBacks_onBuddyStatusCb_set(swigCPtr, this, SWIGTYPE_p_f_int_int_p_q_const__char__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_int_int_p_q_const__char__int getOnBuddyStatusCb() {
    long cPtr = VoxEngineJNI.VX_AppCallBacks_onBuddyStatusCb_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int_int_p_q_const__char__int(cPtr, false);
  }

  public void setOnDtmfDigitCb(SWIGTYPE_p_f_int_int__int value) {
    VoxEngineJNI.VX_AppCallBacks_onDtmfDigitCb_set(swigCPtr, this, SWIGTYPE_p_f_int_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_int_int__int getOnDtmfDigitCb() {
    long cPtr = VoxEngineJNI.VX_AppCallBacks_onDtmfDigitCb_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int_int__int(cPtr, false);
  }

  public void setOnMwiCb(SWIGTYPE_p_f_int_p_char__int value) {
    VoxEngineJNI.VX_AppCallBacks_onMwiCb_set(swigCPtr, this, SWIGTYPE_p_f_int_p_char__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_int_p_char__int getOnMwiCb() {
    long cPtr = VoxEngineJNI.VX_AppCallBacks_onMwiCb_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int_p_char__int(cPtr, false);
  }

  public void setOnCallReplacedCb(SWIGTYPE_p_f_int_int__int value) {
    VoxEngineJNI.VX_AppCallBacks_onCallReplacedCb_set(swigCPtr, this, SWIGTYPE_p_f_int_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_int_int__int getOnCallReplacedCb() {
    long cPtr = VoxEngineJNI.VX_AppCallBacks_onCallReplacedCb_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int_int__int(cPtr, false);
  }

  public void setOnServerResponseCb(SWIGTYPE_p_f_int_int__int value) {
    VoxEngineJNI.VX_AppCallBacks_onServerResponseCb_set(swigCPtr, this, SWIGTYPE_p_f_int_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_int_int__int getOnServerResponseCb() {
    long cPtr = VoxEngineJNI.VX_AppCallBacks_onServerResponseCb_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int_int__int(cPtr, false);
  }

  public void setOnMediaStateCb(SWIGTYPE_p_f_int__int value) {
    VoxEngineJNI.VX_AppCallBacks_onMediaStateCb_set(swigCPtr, this, SWIGTYPE_p_f_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_int__int getOnMediaStateCb() {
    long cPtr = VoxEngineJNI.VX_AppCallBacks_onMediaStateCb_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int__int(cPtr, false);
  }

  public VX_AppCallBacks() {
    this(VoxEngineJNI.new_VX_AppCallBacks(), true);
  }

}
