/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package vx.plt;

public class VX_AppConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VX_AppConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VX_AppConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VoxEngineJNI.delete_VX_AppConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPTime(int value) {
    VoxEngineJNI.VX_AppConfig_pTime_set(swigCPtr, this, value);
  }

  public int getPTime() {
    return VoxEngineJNI.VX_AppConfig_pTime_get(swigCPtr, this);
  }

  public void setSipPort(int value) {
    VoxEngineJNI.VX_AppConfig_sipPort_set(swigCPtr, this, value);
  }

  public int getSipPort() {
    return VoxEngineJNI.VX_AppConfig_sipPort_get(swigCPtr, this);
  }

  public void setProtCfg(int value) {
    VoxEngineJNI.VX_AppConfig_protCfg_set(swigCPtr, this, value);
  }

  public int getProtCfg() {
    return VoxEngineJNI.VX_AppConfig_protCfg_get(swigCPtr, this);
  }

  public void setAppSSL(VX_VoxAppSSL value) {
    VoxEngineJNI.VX_AppConfig_appSSL_set(swigCPtr, this, VX_VoxAppSSL.getCPtr(value), value);
  }

  public VX_VoxAppSSL getAppSSL() {
    long cPtr = VoxEngineJNI.VX_AppConfig_appSSL_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VX_VoxAppSSL(cPtr, false);
  }

  public void setLogLevel(int value) {
    VoxEngineJNI.VX_AppConfig_logLevel_set(swigCPtr, this, value);
  }

  public int getLogLevel() {
    return VoxEngineJNI.VX_AppConfig_logLevel_get(swigCPtr, this);
  }

  public void setMax_calls(int value) {
    VoxEngineJNI.VX_AppConfig_max_calls_set(swigCPtr, this, value);
  }

  public int getMax_calls() {
    return VoxEngineJNI.VX_AppConfig_max_calls_get(swigCPtr, this);
  }

  public void setLogfileName(String value) {
    VoxEngineJNI.VX_AppConfig_logfileName_set(swigCPtr, this, value);
  }

  public String getLogfileName() {
    return VoxEngineJNI.VX_AppConfig_logfileName_get(swigCPtr, this);
  }

  public void setAppCbks(VX_AppCallBacks value) {
    VoxEngineJNI.VX_AppConfig_appCbks_set(swigCPtr, this, VX_AppCallBacks.getCPtr(value), value);
  }

  public VX_AppCallBacks getAppCbks() {
    long cPtr = VoxEngineJNI.VX_AppConfig_appCbks_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VX_AppCallBacks(cPtr, false);
  }

  public void setUser_agent(String value) {
    VoxEngineJNI.VX_AppConfig_user_agent_set(swigCPtr, this, value);
  }

  public String getUser_agent() {
    return VoxEngineJNI.VX_AppConfig_user_agent_get(swigCPtr, this);
  }

  public void setEc_option(int value) {
    VoxEngineJNI.VX_AppConfig_ec_option_set(swigCPtr, this, value);
  }

  public int getEc_option() {
    return VoxEngineJNI.VX_AppConfig_ec_option_get(swigCPtr, this);
  }

  public void setJb_type(int value) {
    VoxEngineJNI.VX_AppConfig_jb_type_set(swigCPtr, this, value);
  }

  public int getJb_type() {
    return VoxEngineJNI.VX_AppConfig_jb_type_get(swigCPtr, this);
  }

  public void setInterface_type(int value) {
    VoxEngineJNI.VX_AppConfig_interface_type_set(swigCPtr, this, value);
  }

  public int getInterface_type() {
    return VoxEngineJNI.VX_AppConfig_interface_type_get(swigCPtr, this);
  }

  public void setIsAECAvailable(int value) {
    VoxEngineJNI.VX_AppConfig_isAECAvailable_set(swigCPtr, this, value);
  }

  public int getIsAECAvailable() {
    return VoxEngineJNI.VX_AppConfig_isAECAvailable_get(swigCPtr, this);
  }

  public void setIsNSAvailable(int value) {
    VoxEngineJNI.VX_AppConfig_isNSAvailable_set(swigCPtr, this, value);
  }

  public int getIsNSAvailable() {
    return VoxEngineJNI.VX_AppConfig_isNSAvailable_get(swigCPtr, this);
  }

  public void setIsAGCAvailable(int value) {
    VoxEngineJNI.VX_AppConfig_isAGCAvailable_set(swigCPtr, this, value);
  }

  public int getIsAGCAvailable() {
    return VoxEngineJNI.VX_AppConfig_isAGCAvailable_get(swigCPtr, this);
  }

  public void setClockRate(int value) {
    VoxEngineJNI.VX_AppConfig_ClockRate_set(swigCPtr, this, value);
  }

  public int getClockRate() {
    return VoxEngineJNI.VX_AppConfig_ClockRate_get(swigCPtr, this);
  }

  public void setIsAndroid_2_x_Version(int value) {
    VoxEngineJNI.VX_AppConfig_isAndroid_2_x_Version_set(swigCPtr, this, value);
  }

  public int getIsAndroid_2_x_Version() {
    return VoxEngineJNI.VX_AppConfig_isAndroid_2_x_Version_get(swigCPtr, this);
  }

  public void setStun_srv_count(int value) {
    VoxEngineJNI.VX_AppConfig_stun_srv_count_set(swigCPtr, this, value);
  }

  public int getStun_srv_count() {
    return VoxEngineJNI.VX_AppConfig_stun_srv_count_get(swigCPtr, this);
  }

  public void setApp_name(String value) {
    VoxEngineJNI.VX_AppConfig_app_name_set(swigCPtr, this, value);
  }

  public String getApp_name() {
    return VoxEngineJNI.VX_AppConfig_app_name_get(swigCPtr, this);
  }

  public VX_AppConfig() {
    this(VoxEngineJNI.new_VX_AppConfig(), true);
  }

}
