/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package vx.plt;

public class VX_CallInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VX_CallInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VX_CallInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VoxEngineJNI.delete_VX_CallInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMemberName(String value) {
    VoxEngineJNI.VX_CallInfo_memberName_set(swigCPtr, this, value);
  }

  public String getMemberName() {
    return VoxEngineJNI.VX_CallInfo_memberName_get(swigCPtr, this);
  }

  public void setCallState(int value) {
    VoxEngineJNI.VX_CallInfo_callState_set(swigCPtr, this, value);
  }

  public int getCallState() {
    return VoxEngineJNI.VX_CallInfo_callState_get(swigCPtr, this);
  }

  public void setLocal_info(String value) {
    VoxEngineJNI.VX_CallInfo_local_info_set(swigCPtr, this, value);
  }

  public String getLocal_info() {
    return VoxEngineJNI.VX_CallInfo_local_info_get(swigCPtr, this);
  }

  public void setLocal_contact(String value) {
    VoxEngineJNI.VX_CallInfo_local_contact_set(swigCPtr, this, value);
  }

  public String getLocal_contact() {
    return VoxEngineJNI.VX_CallInfo_local_contact_get(swigCPtr, this);
  }

  public void setRemote_info(String value) {
    VoxEngineJNI.VX_CallInfo_remote_info_set(swigCPtr, this, value);
  }

  public String getRemote_info() {
    return VoxEngineJNI.VX_CallInfo_remote_info_get(swigCPtr, this);
  }

  public void setRemote_contact(String value) {
    VoxEngineJNI.VX_CallInfo_remote_contact_set(swigCPtr, this, value);
  }

  public String getRemote_contact() {
    return VoxEngineJNI.VX_CallInfo_remote_contact_get(swigCPtr, this);
  }

  public void setCall_id(String value) {
    VoxEngineJNI.VX_CallInfo_call_id_set(swigCPtr, this, value);
  }

  public String getCall_id() {
    return VoxEngineJNI.VX_CallInfo_call_id_get(swigCPtr, this);
  }

  public void setLast_status_text(String value) {
    VoxEngineJNI.VX_CallInfo_last_status_text_set(swigCPtr, this, value);
  }

  public String getLast_status_text() {
    return VoxEngineJNI.VX_CallInfo_last_status_text_get(swigCPtr, this);
  }

  public void setCall_dump(String value) {
    VoxEngineJNI.VX_CallInfo_call_dump_set(swigCPtr, this, value);
  }

  public String getCall_dump() {
    return VoxEngineJNI.VX_CallInfo_call_dump_get(swigCPtr, this);
  }

  public void setStatus_code(int value) {
    VoxEngineJNI.VX_CallInfo_status_code_set(swigCPtr, this, value);
  }

  public int getStatus_code() {
    return VoxEngineJNI.VX_CallInfo_status_code_get(swigCPtr, this);
  }

  public void setConnect_duration(int value) {
    VoxEngineJNI.VX_CallInfo_connect_duration_set(swigCPtr, this, value);
  }

  public int getConnect_duration() {
    return VoxEngineJNI.VX_CallInfo_connect_duration_get(swigCPtr, this);
  }

  public void setTotal_duration(int value) {
    VoxEngineJNI.VX_CallInfo_total_duration_set(swigCPtr, this, value);
  }

  public int getTotal_duration() {
    return VoxEngineJNI.VX_CallInfo_total_duration_get(swigCPtr, this);
  }

  public VX_CallInfo() {
    this(VoxEngineJNI.new_VX_CallInfo(), true);
  }

}
