/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package vx.plt;

public class VX_CodecInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VX_CodecInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VX_CodecInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VoxEngineJNI.delete_VX_CodecInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCodecName(String value) {
    VoxEngineJNI.VX_CodecInfo_codecName_set(swigCPtr, this, value);
  }

  public String getCodecName() {
    return VoxEngineJNI.VX_CodecInfo_codecName_get(swigCPtr, this);
  }

  public void setIndex(int value) {
    VoxEngineJNI.VX_CodecInfo_index_set(swigCPtr, this, value);
  }

  public int getIndex() {
    return VoxEngineJNI.VX_CodecInfo_index_get(swigCPtr, this);
  }

  public VX_CodecInfo() {
    this(VoxEngineJNI.new_VX_CodecInfo(), true);
  }

}
