/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package vx.plt;

public enum VX_DataBase_STATUS {
  VX_MEMBER_NAME_CHANGED,
  VX_CONTACT_ADDED,
  VX_CONTACT_DELETED,
  VX_CONTACT_RENAMED,
  VX_CONTACT_LIST_UPDATED,
  VX_CONTACT_UPDATED,
  VX_INVALID_STATUS;

  public final int swigValue() {
    return swigValue;
  }

  public static VX_DataBase_STATUS swigToEnum(int swigValue) {
    VX_DataBase_STATUS[] swigValues = VX_DataBase_STATUS.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (VX_DataBase_STATUS swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + VX_DataBase_STATUS.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private VX_DataBase_STATUS() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private VX_DataBase_STATUS(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private VX_DataBase_STATUS(VX_DataBase_STATUS swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

