/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package vx.plt;

public enum VX_ENCRYPT_TYPE {
  OLD,
  NEW,
  LATEST,
  MODERN;

  public final int swigValue() {
    return swigValue;
  }

  public static VX_ENCRYPT_TYPE swigToEnum(int swigValue) {
    VX_ENCRYPT_TYPE[] swigValues = VX_ENCRYPT_TYPE.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (VX_ENCRYPT_TYPE swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + VX_ENCRYPT_TYPE.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private VX_ENCRYPT_TYPE() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private VX_ENCRYPT_TYPE(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private VX_ENCRYPT_TYPE(VX_ENCRYPT_TYPE swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

