/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package vx.plt;

public enum VX_ERROR {
  VX_FAILURE(0),
  VX_SUCCESS,
  VX_APP_NOT_INITIALIZED,
  VX_MEMORY_ALLOCATION_FAILED,
  VX_NULL_POINTER,
  VX_MEMORY_UNAVAILABLE,
  VX_NOT_LOGGED_IN,
  VX_APP_INIT_FAILED,
  VX_INTERNAL_ERROR,
  VX_FEATURE_NOT_SUPPORTED,
  VX_ERROR_MAX_ID;

  public final int swigValue() {
    return swigValue;
  }

  public static VX_ERROR swigToEnum(int swigValue) {
    VX_ERROR[] swigValues = VX_ERROR.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (VX_ERROR swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + VX_ERROR.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private VX_ERROR() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private VX_ERROR(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private VX_ERROR(VX_ERROR swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

