/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package vx.plt;

public enum VX_FEATURE {
  VX_AUDIO_CALL,
  VX_VIDEO_CALL;

  public final int swigValue() {
    return swigValue;
  }

  public static VX_FEATURE swigToEnum(int swigValue) {
    VX_FEATURE[] swigValues = VX_FEATURE.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (VX_FEATURE swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + VX_FEATURE.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private VX_FEATURE() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private VX_FEATURE(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private VX_FEATURE(VX_FEATURE swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

