/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package vx.plt;

public enum VX_INVITE_State {
  VX_INV_STATE_NULL,
  VX_INV_STATE_CALLING,
  VX_INV_STATE_INCOMING,
  VX_INV_STATE_EARLY,
  VX_INV_STATE_CONNECTING,
  VX_INV_STATE_CONFIRMED,
  VX_INV_STATE_DISCONNECTED;

  public final int swigValue() {
    return swigValue;
  }

  public static VX_INVITE_State swigToEnum(int swigValue) {
    VX_INVITE_State[] swigValues = VX_INVITE_State.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (VX_INVITE_State swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + VX_INVITE_State.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private VX_INVITE_State() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private VX_INVITE_State(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private VX_INVITE_State(VX_INVITE_State swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

