/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package vx.plt;

public class VX_LogConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VX_LogConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VX_LogConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VoxEngineJNI.delete_VX_LogConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLogLevel(int value) {
    VoxEngineJNI.VX_LogConfig_logLevel_set(swigCPtr, this, value);
  }

  public int getLogLevel() {
    return VoxEngineJNI.VX_LogConfig_logLevel_get(swigCPtr, this);
  }

  public void setLogfileName(String value) {
    VoxEngineJNI.VX_LogConfig_logfileName_set(swigCPtr, this, value);
  }

  public String getLogfileName() {
    return VoxEngineJNI.VX_LogConfig_logfileName_get(swigCPtr, this);
  }

  public void setMsg_logging(int value) {
    VoxEngineJNI.VX_LogConfig_msg_logging_set(swigCPtr, this, value);
  }

  public int getMsg_logging() {
    return VoxEngineJNI.VX_LogConfig_msg_logging_get(swigCPtr, this);
  }

  public void setLog_console_level(long value) {
    VoxEngineJNI.VX_LogConfig_log_console_level_set(swigCPtr, this, value);
  }

  public long getLog_console_level() {
    return VoxEngineJNI.VX_LogConfig_log_console_level_get(swigCPtr, this);
  }

  public void setDecor(long value) {
    VoxEngineJNI.VX_LogConfig_decor_set(swigCPtr, this, value);
  }

  public long getDecor() {
    return VoxEngineJNI.VX_LogConfig_decor_get(swigCPtr, this);
  }

  public void setLog_file_flags(long value) {
    VoxEngineJNI.VX_LogConfig_log_file_flags_set(swigCPtr, this, value);
  }

  public long getLog_file_flags() {
    return VoxEngineJNI.VX_LogConfig_log_file_flags_get(swigCPtr, this);
  }

  public VX_LogConfig() {
    this(VoxEngineJNI.new_VX_LogConfig(), true);
  }

}
