/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package vx.plt;

public class VX_PRESENCE_STATE {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VX_PRESENCE_STATE(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VX_PRESENCE_STATE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VoxEngineJNI.delete_VX_PRESENCE_STATE(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setState(VX_PRESENCE value) {
    VoxEngineJNI.VX_PRESENCE_STATE_state_set(swigCPtr, this, value.swigValue());
  }

  public VX_PRESENCE getState() {
    return VX_PRESENCE.swigToEnum(VoxEngineJNI.VX_PRESENCE_STATE_state_get(swigCPtr, this));
  }

  public void setName(String value) {
    VoxEngineJNI.VX_PRESENCE_STATE_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return VoxEngineJNI.VX_PRESENCE_STATE_name_get(swigCPtr, this);
  }

  public VX_PRESENCE_STATE() {
    this(VoxEngineJNI.new_VX_PRESENCE_STATE(), true);
  }

}
