/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package vx.plt;

public class VX_SipConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VX_SipConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VX_SipConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VoxEngineJNI.delete_VX_SipConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNoUDP(int value) {
    VoxEngineJNI.VX_SipConfig_noUDP_set(swigCPtr, this, value);
  }

  public int getNoUDP() {
    return VoxEngineJNI.VX_SipConfig_noUDP_get(swigCPtr, this);
  }

  public void setNoTCP(int value) {
    VoxEngineJNI.VX_SipConfig_noTCP_set(swigCPtr, this, value);
  }

  public int getNoTCP() {
    return VoxEngineJNI.VX_SipConfig_noTCP_get(swigCPtr, this);
  }

  public void setPublishEnabled(int value) {
    VoxEngineJNI.VX_SipConfig_publishEnabled_set(swigCPtr, this, value);
  }

  public int getPublishEnabled() {
    return VoxEngineJNI.VX_SipConfig_publishEnabled_get(swigCPtr, this);
  }

  public void setVadEnabled(int value) {
    VoxEngineJNI.VX_SipConfig_vadEnabled_set(swigCPtr, this, value);
  }

  public int getVadEnabled() {
    return VoxEngineJNI.VX_SipConfig_vadEnabled_get(swigCPtr, this);
  }

  public void setPollingEventsEnabled(int value) {
    VoxEngineJNI.VX_SipConfig_pollingEventsEnabled_set(swigCPtr, this, value);
  }

  public int getPollingEventsEnabled() {
    return VoxEngineJNI.VX_SipConfig_pollingEventsEnabled_get(swigCPtr, this);
  }

  public void setImsEnabled(int value) {
    VoxEngineJNI.VX_SipConfig_imsEnabled_set(swigCPtr, this, value);
  }

  public int getImsEnabled() {
    return VoxEngineJNI.VX_SipConfig_imsEnabled_get(swigCPtr, this);
  }

  public void setImsIPSecHeaders(int value) {
    VoxEngineJNI.VX_SipConfig_imsIPSecHeaders_set(swigCPtr, this, value);
  }

  public int getImsIPSecHeaders() {
    return VoxEngineJNI.VX_SipConfig_imsIPSecHeaders_get(swigCPtr, this);
  }

  public void setImsIPSecTransport(int value) {
    VoxEngineJNI.VX_SipConfig_imsIPSecTransport_set(swigCPtr, this, value);
  }

  public int getImsIPSecTransport() {
    return VoxEngineJNI.VX_SipConfig_imsIPSecTransport_get(swigCPtr, this);
  }

  public void setListenPort(int value) {
    VoxEngineJNI.VX_SipConfig_listenPort_set(swigCPtr, this, value);
  }

  public int getListenPort() {
    return VoxEngineJNI.VX_SipConfig_listenPort_get(swigCPtr, this);
  }

  public void setExpires(int value) {
    VoxEngineJNI.VX_SipConfig_expires_set(swigCPtr, this, value);
  }

  public int getExpires() {
    return VoxEngineJNI.VX_SipConfig_expires_get(swigCPtr, this);
  }

  public void setEcTail(int value) {
    VoxEngineJNI.VX_SipConfig_ecTail_set(swigCPtr, this, value);
  }

  public int getEcTail() {
    return VoxEngineJNI.VX_SipConfig_ecTail_get(swigCPtr, this);
  }

  public void setLogLevel(int value) {
    VoxEngineJNI.VX_SipConfig_logLevel_set(swigCPtr, this, value);
  }

  public int getLogLevel() {
    return VoxEngineJNI.VX_SipConfig_logLevel_get(swigCPtr, this);
  }

  public void setStunAddress(String value) {
    VoxEngineJNI.VX_SipConfig_stunAddress_set(swigCPtr, this, value);
  }

  public String getStunAddress() {
    return VoxEngineJNI.VX_SipConfig_stunAddress_get(swigCPtr, this);
  }

  public void setNameServer(String value) {
    VoxEngineJNI.VX_SipConfig_nameServer_set(swigCPtr, this, value);
  }

  public String getNameServer() {
    return VoxEngineJNI.VX_SipConfig_nameServer_get(swigCPtr, this);
  }

  public VX_SipConfig() {
    this(VoxEngineJNI.new_VX_SipConfig(), true);
  }

}
