/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package vx.plt;

public enum VX_SHUTDOWN_REASON {
  VX_SHUTDOWN_USER_INITIATED,
  VX_SHUTDOWN_FORCE_EXIT,
  VX_SHUTDOWN_INVALID_REASON;

  public final int swigValue() {
    return swigValue;
  }

  public static VX_SHUTDOWN_REASON swigToEnum(int swigValue) {
    VX_SHUTDOWN_REASON[] swigValues = VX_SHUTDOWN_REASON.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (VX_SHUTDOWN_REASON swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + VX_SHUTDOWN_REASON.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private VX_SHUTDOWN_REASON() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private VX_SHUTDOWN_REASON(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private VX_SHUTDOWN_REASON(VX_SHUTDOWN_REASON swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

