/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package vx.plt;

public class VX_TransferInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VX_TransferInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VX_TransferInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VoxEngineJNI.delete_VX_TransferInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCallid(SWIGTYPE_p_int value) {
    VoxEngineJNI.VX_TransferInfo_callid_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getCallid() {
    long cPtr = VoxEngineJNI.VX_TransferInfo_callid_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setVx_transferType(VX_TransferType value) {
    VoxEngineJNI.VX_TransferInfo_vx_transferType_set(swigCPtr, this, value.swigValue());
  }

  public VX_TransferType getVx_transferType() {
    return VX_TransferType.swigToEnum(VoxEngineJNI.VX_TransferInfo_vx_transferType_get(swigCPtr, this));
  }

  public VX_TransferInfo() {
    this(VoxEngineJNI.new_VX_TransferInfo(), true);
  }

}
