/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package vx.plt;

public class VX_VoxAppSSL {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VX_VoxAppSSL(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VX_VoxAppSSL obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VoxEngineJNI.delete_VX_VoxAppSSL(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEType(VX_ENCRYPT_TYPE value) {
    VoxEngineJNI.VX_VoxAppSSL_eType_set(swigCPtr, this, value.swigValue());
  }

  public VX_ENCRYPT_TYPE getEType() {
    return VX_ENCRYPT_TYPE.swigToEnum(VoxEngineJNI.VX_VoxAppSSL_eType_get(swigCPtr, this));
  }

  public void setIVpnTrigger(int value) {
    VoxEngineJNI.VX_VoxAppSSL_iVpnTrigger_set(swigCPtr, this, value);
  }

  public int getIVpnTrigger() {
    return VoxEngineJNI.VX_VoxAppSSL_iVpnTrigger_get(swigCPtr, this);
  }

  public void setIStarting(int value) {
    VoxEngineJNI.VX_VoxAppSSL_iStarting_set(swigCPtr, this, value);
  }

  public int getIStarting() {
    return VoxEngineJNI.VX_VoxAppSSL_iStarting_get(swigCPtr, this);
  }

  public void setILength(int value) {
    VoxEngineJNI.VX_VoxAppSSL_iLength_set(swigCPtr, this, value);
  }

  public int getILength() {
    return VoxEngineJNI.VX_VoxAppSSL_iLength_get(swigCPtr, this);
  }

  public void setIPrefTrigger(int value) {
    VoxEngineJNI.VX_VoxAppSSL_iPrefTrigger_set(swigCPtr, this, value);
  }

  public int getIPrefTrigger() {
    return VoxEngineJNI.VX_VoxAppSSL_iPrefTrigger_get(swigCPtr, this);
  }

  public void setIPrefValue(int value) {
    VoxEngineJNI.VX_VoxAppSSL_iPrefValue_set(swigCPtr, this, value);
  }

  public int getIPrefValue() {
    return VoxEngineJNI.VX_VoxAppSSL_iPrefValue_get(swigCPtr, this);
  }

  public void setINoOfInnerPref(int value) {
    VoxEngineJNI.VX_VoxAppSSL_iNoOfInnerPref_set(swigCPtr, this, value);
  }

  public int getINoOfInnerPref() {
    return VoxEngineJNI.VX_VoxAppSSL_iNoOfInnerPref_get(swigCPtr, this);
  }

  public void setINoOfPref(int value) {
    VoxEngineJNI.VX_VoxAppSSL_iNoOfPref_set(swigCPtr, this, value);
  }

  public int getINoOfPref() {
    return VoxEngineJNI.VX_VoxAppSSL_iNoOfPref_get(swigCPtr, this);
  }

  public void setIDiff(int value) {
    VoxEngineJNI.VX_VoxAppSSL_iDiff_set(swigCPtr, this, value);
  }

  public int getIDiff() {
    return VoxEngineJNI.VX_VoxAppSSL_iDiff_get(swigCPtr, this);
  }

  public void setOldkey(String value) {
    VoxEngineJNI.VX_VoxAppSSL_oldkey_set(swigCPtr, this, value);
  }

  public String getOldkey() {
    return VoxEngineJNI.VX_VoxAppSSL_oldkey_get(swigCPtr, this);
  }

  public VX_VoxAppSSL() {
    this(VoxEngineJNI.new_VX_VoxAppSSL(), true);
  }

}
